name: Node.js CI

on: [push]

jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    strategy:
#      matrix:
#        node-version: [12.x]
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: Use Node.js ${{ matrix.node-version }}
#        uses: actions/setup-node@v1
#        with:
#          node-version: ${{ matrix.node-version }}
#      - run: npm install
#      - run: npm run build --if-present
#        env:
#          CI: true

#      - name: Upload dist/
#        uses: actions/upload-artifact@v1
#        with:
#          name: folderwork
#          path: dist/

  deploy:
    name: Deploy to remote server
#    needs: build
    runs-on: ubuntu-latest

    steps:
#      - name: Download folderwork
#        uses: actions/download-artifact@v1
#        with:
#          name: folderwork

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SecretKey }}
          script: |
            cd ~/react-redux-boilerplate
            git pull
            npm i
            npm run build

